import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { connectMongoDB } from '@/libs/mongodb/Connect';
import Task from '@/libs/mongodb/TaskModel';

export default function Home({ tasks }) {
	return (
		<>
			<Head>
				<title>Todo Next and Mongoose app</title>
				<meta
					name='description'
					content='A todo application that uses the MngoDB Atlas database, generated by create next app'
				/>
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<h1>This is home</h1>
				{tasks.map(({ _id, task, description, date }) => (
					<div key={_id}>
						<h2>{task}</h2>
						<p>{description}</p>
						<p>{date}</p>
					</div>
				))}
			</main>
		</>
	);
}

export async function getStaticProps() {
	await connectMongoDB();
	const data = await Task.find();
	const tasks = JSON.parse(JSON.stringify(data));

	return {
		props: {
			tasks,
		},
	};
}
